### ISSUE TITLE
How did you get it to use text message instead of embed? And without an image for every embed reply

### ISSUE THREAD

**Issue by just-rich** [onury5506/Discord-ChatGPT-Bot#13]
In your screenshots it's not using an embed to reply. It's also adding an image to every embed.

How can I get it to just use regular text messages?

**Comment by onury5506** [comment]
You can set "USE_EMBED" option to false and be sure you using latest version.

**Comment by just-rich** [comment]
> You can set "USE_EMBED" option to false and be sure you using latest version.

In the .env config?

**Comment by onury5506** [comment]
Yes in the .env config file

**Comment by just-rich** [comment]
> Yes in the .env config file

Didn't work

**Comment by just-rich** [comment]
DISCORD_BOT_TOKEN=xxx
DISCORD_CLIENT_ID=xxx
OPENAI_API_KEY=xxx
ENABLE_DIRECT_MESSAGES=false
CONVERSATION_MEMORY_SECONDS=300
CONVERSATION_START_PROMPT=false
USE_EMBED=false

**Comment by onury5506** [comment]
I pushed it a few minutes ago, update it

**Comment by just-rich** [comment]
Appreciate it, thanks!

**Comment by onury5506** [comment]
You are welcome!
