### ISSUE TITLE
Bot returns a ooops image after think when asked a question!

### ISSUE THREAD

**Issue by ai4bing** [onury5506/Discord-ChatGPT-Bot#14]
I'm not sure if I misused it, but this is what happened to me. How do I fixed this?

<img src="https://user-images.githubusercontent.com/76109691/219117249-992c926a-0cca-43fb-b3bd-a98afef89128.jpg" width="300" height="292.5">  <img src="https://user-images.githubusercontent.com/76109691/219118242-5d657882-d9a0-4198-8f60-d0be8f8728cf.jpg" width="390" height="292.5">

**Comment by onury5506** [comment]
"oops something went wrong! (error)" is an error message for chatgpt. The bot returns this message when the user asks a question and chatgpt cannot respond. And it also generates an image for the response in the embed system. If you don't want to use the embed style, you can use the classic message style by setting "USE_EMBED" to false.

**Comment by ai4bing** [comment]
Ok, but even when I enter 'Hi', ChatGPT responds this way.
Is this related to my OpenAI API, or is it just an issue within ChatGPT?

**Comment by onury5506** [comment]
Do you use latest version of the bot?

**Comment by onury5506** [comment]
Okey then check yout openai account, does it have free credits or is it billable account?

**Comment by ai4bing** [comment]
Oh, do I need free credits to use it?! Thank you for your explanation! This comment can be closed.
