### ISSUE TITLE
Bot attaches images to messages without input

### ISSUE THREAD

**Issue by litbeep** [onury5506/Discord-ChatGPT-Bot#16]
After asking any question, the bot will automatically edit the message and add an AI-generated image several minutes later. It seems to happen on all responses sent by the bot.

![image](https://user-images.githubusercontent.com/86410807/219796819-a19580d4-5511-4215-bcc9-0241eb6d1ab0.png)

**Comment by wsimon98** [comment]
yeah. super annoying. hopefully this gets fixed.

**Comment by onury5506** [comment]
You can disable it by setting "USE_EMBED" to false.

**Comment by wsimon98** [comment]
where would that option be?
