### ISSUE TITLE
Invalid token was provided

### ISSUE THREAD

**Issue by uurx** [onury5506/Discord-ChatGPT-Bot#17]
I'm sure that my tokens are correct and everything is okay but still it gives this error can someone help?
![image](https://user-images.githubusercontent.com/111447584/219961525-4e67604f-496d-4276-9aa4-85443d1d95d4.png)

**Comment by uurx** [comment]
I fix it however when I try to use it, it sends this message always. I can't use any commands but i can use it in direct message.
![image](https://user-images.githubusercontent.com/111447584/220214929-4df4edee-c2e7-404b-bf82-2ac2bbfbf373.png)

**Comment by rhaym-tech** [comment]
Please close your issue, since you fixed it

**Comment by onury5506** [comment]
@uurx please try the new version, the new version doesn't use openai API key.
