### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by ManucrackYT** [onury5506/Discord-ChatGPT-Bot#24]
This happens when im asking something to the bot using GPT-3.5-turbo, is there a free plan to use ChatGPT?

**Comment by onury5506** [comment]
OpenAI does not offer a free plan, but it does provide a $5 credit for new accounts that are created with a new phone number.

**Comment by ManucrackYT** [comment]
Where can i get the 5$ credit? I registered a week ago with phone number

**Comment by onury5506** [comment]
It should be granted when you create the account. But be sure you don't use the same phone number twice. Only the first account will be granted.
