### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by amasoiD** [onury5506/Discord-ChatGPT-Bot#3]
npm start

> chatgpt-discordjs@1.0.0 start
> node index.js

initChatGPT ERROR : TimeoutError: Waiting for selector `#__next > div > div > div.flex.flex-row.gap-3 > button:nth-child(1)` failed: Waiting failed: 30000ms exceeded

**Comment by topapoo** [comment]
Same

**Comment by onury5506** [comment]
Hi, it should be solved, try again please if have any problem you can ask on discord server.
