### ISSUE TITLE
DM's not registering

### ISSUE THREAD

**Issue by FishyMine** [onury5506/Discord-ChatGPT-Bot#32]
What the title says, exactly.
![image](https://user-images.githubusercontent.com/72989672/236861114-57dea903-f79f-48f5-af51-b2ab617cb28a.png)
![image](https://user-images.githubusercontent.com/72989672/236861139-1a205f30-4d8c-427f-93a2-b311e20f761d.png)
![image](https://user-images.githubusercontent.com/72989672/236861236-d57170ab-53dd-463d-adc4-6f1e1abe9096.png)

**Comment by onury5506** [comment]
Yes, you are right, I will check and fix it. Thank you for your feedback.

**Comment by FishyMine** [comment]
> Yes, you are right, I will check and fix it. Thank you for your feedback.

Alright

**Comment by onury5506** [comment]
The bug is fixed
