### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by RageMonke06** [onury5506/Discord-ChatGPT-Bot#4]
When I start the bot using `npm start` I get this error and don't know how to fix it. Pls help

Error:
`initChatGPT ERROR : TimeoutError: Waiting for selector `#__next > div > div > div.flex.flex-row.gap-3 > button:nth-child(1)` failed: Waiting failed: 30000ms exceeded`

**Comment by onury5506** [comment]
Hello new version released try it! If you have any problems you can ask it on discord server.
