### ISSUE TITLE
Issue with my bot in discord

### ISSUE THREAD

**Issue by sanjayk0508** [onury5506/Discord-ChatGPT-Bot#7]
The discord bot is working absolutely amazing. I made my own bot using the same code from the github repo and followed every single thing in order to run my own bot, But I do have some issues with my bot though,

ISSUE: Whenever i have to interact with the bot i have to run 'npm start' and keep the terminal & chrome open (with ChatGPT logged in) or else the bot goes offline. 

I want my bot to continuously work even if i stop the terminal

I would be more than happy if anyone can help me out.

**Comment by BLACK4585** [comment]
I think there is nothing you can do atm. Thats how the system works right now. Until the official API launches, I dont think there is anything the auther can change.
